### ISSUE TITLE
When I launch the app in android it crashes with: couldn't find "libNativeScript.so"

### ISSUE THREAD

**Issue by giordy** [telerik/nativescript-ui-samples-angular#23]
Hi,

I'm getting this output from logcat:

```
--------- beginning of crash
08-01 15:41:13.880  2845  2845 E AndroidRuntime: FATAL EXCEPTION: main
08-01 15:41:13.880  2845  2845 E AndroidRuntime: Process: org.nativescript.sdkAngular, PID: 2845
08-01 15:41:13.880  2845  2845 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.nativescript.sdkAngular-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.sdkAngular-1/lib/x86_64, /data/app/org.nativescript.sdkAngular-1/base.apk!/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libNativeScript.so"
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:43)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:15)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-01 15:41:13.880  2845  2845 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-01 15:41:13.881  1531  2236 W ActivityManager:   Force finishing activity org.nativescript.sdkAngular/com.tns.NativeScriptActivity
08-01 15:41:14.182  1531  2236 I WindowManager: Screenshot max retries 4 of Token{4a3fc3 ActivityRecord{35cf72 u0 org.nativescript.sdkAngular/com.tns.NativeScriptActivity t73 f}} appWin=Window{c91e43b u0 Starting org.nativescript.sdkAngular} drawState=3
08-01 15:41:14.183  1531  1531 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 290ms
08-01 15:41:14.222  1531  1578 I OpenGLRenderer: Initialized EGL, version 1.4
08-01 15:41:14.683  1531  1545 W ActivityManager: Activity pause timeout for ActivityRecord{35cf72 u0 org.nativescript.sdkAngular/com.tns.NativeScriptActivity t73 f}
08-01 15:41:24.712  1531  1545 W ActivityManager: Activity destroy timeout for ActivityRecord{35cf72 u0 org.nativescript.sdkAngular/com.tns.NativeScriptActivity t73 f}
08-01 15:42:34.117  2845  2845 I Process : Sending signal. PID: 2845 SIG: 9
08-01 15:42:34.134  1531  1578 E Surface : getSlotFromBufferLocked: unknown buffer: 0x7f2a50e8d3b0
08-01 15:42:34.137  1531  1578 D OpenGLRenderer: endAllStagingAnimators on 0x7f2a41c4e400 (RippleDrawable) with handle 0x7f2a3f67d820
08-01 15:42:34.140  1531  1543 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@154d446 attribute=null, token = android.os.BinderProxy@cacd99c
08-01 15:42:34.170  1531  1996 I ActivityManager: Process org.nativescript.sdkAngular (pid 2845) has died
08-01 15:42:34.317  1531  1550 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
```
I'm using tns version 2.1.1

**Comment by VladimirAmiorkov** [comment]
Hi @ginev ,

I just tested the repo with the latest nativescript **2.2.1** and was able to run the sample project on both Android and iOS without any trouble. Could you try to:

1. Clean your {N} project. Delete the lib, platforms and node_modules folders
2. Update to the latest nativescript version `npm install -g nativescript` , more info about the upgrade process can be found [here](http://docs.nativescript.org/releases/upgrade-instructions)

If you continue to get the mentioned error could you share with us more details about the environment on which you are testing the repo.

**Comment by VladimirAmiorkov** [comment]
Closing this issue for now. 

If you continue getting the discussed error let us know by reopening and providing additional information.
